FROM node:16 as builder
RUN mkdir /frontend
WORKDIR /frontend
COPY package.json /frontend/package.json
RUN npm install --registry=https://registry.npm.taobao.org
COPY . /frontend
RUN npm run build
RUN npm install -g serve