version: '3'

services:
  api:
    build: api
    command: ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]
    volumes:
      - ./api:/backend
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  client:
    build: client
    command: ["serve", "-s", "build"]
    volumes:
      - ./client:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  node-modules: